baseURL = "http://localhost"
copyright = "© 2020 Michael Schnerring"
title = "Michael Schnerring"
#paginate = 10
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This setting allows inlining <script> and <style> tags in markdown,
      # which is useful and required to use Prism plugins, but may be dangerous
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP quality
  quality = 90

[params]
  # dark or light, defaults to light
  defaultTheme = "dark"
  # gray red green yellow blue purple aqua orange, defaults to blue
  themeColor = "aqua"
  # soft medium hard, defaults to medium
  themeContrast = "hard"
  author = "Michael Schnerring"
  subtitle = "Software Engineer"
  description = "Michael Schnerring is a coder and computer enthusiast."

  # Plausible auth secret to enable public dashboard
  plausibleAuth = "hDl_ZT_txy4BS608-H3Y0"

  [params.logo]
    text = "schnerring.net"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "csharp",
      "hcl",
      "ignore",
      "json",
      "markdown",
      "powershell",
      "toml",
      "yaml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "command-line"
    ]

  # Social share links for posts:
  #   - icon from the Simple Icons suite except "Email" from Tabler Icons
  #   - {url} is replaced with .Permalink
  #   - {title} is replaced with .Title
  # See also: https://github.com/bradvin/social-share-urls
  [[params.socialShare]]
    icon = "Facebook"
    formatString = "https://www.facebook.com/sharer.php?u={url}"
  [[params.socialShare]]
    icon = "Reddit"
    formatString = "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    icon = "Twitter"
    formatString = "https://twitter.com/intent/tweet?url={url}&text={title}"
  [[params.socialShare]]
    icon = "LinkedIn"
    formatString = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
  [[params.socialShare]]
    icon = "WhatsApp"
    formatString = "whatsapp://send/?text={title}%20{url}"
  [[params.socialShare]]
    icon = "Tumblr"
    formatString = "https://www.tumblr.com/widgets/share/tool?canonicalUrl={url}&title={title}&caption={title}"
  [[params.socialShare]]
    icon = "Pinterest"
    formatString = "http://pinterest.com/pin/create/button/?url={url}"
  [[params.socialShare]]
    icon = "YCombinator"
    formatString = "https://news.ycombinator.com/submitlink?u={url}&t={title}"
  [[params.socialShare]]
    icon = "VK"
    formatString = "http://vk.com/share.php?url={url}&title={title}&comment={title}"
  [[params.socialShare]]
    icon = "XING"
    formatString = "https://www.xing.com/spi/shares/new?url={url}"
  [[params.socialShare]]
    icon = "Telegram"
    formatString = "https://telegram.me/share/url?url={url}&text={title}"
  [[params.socialShare]]
    icon = "Mail"
    formatString = "mailto:?subject={title}&body={url}"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40
  [[menu.main]]
    identifier = "stats"
    name = "Stats"
    url = "/stats"
    weight = 50

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params.jsonResume]
      present = "present"
  [languages.de]
    languageName = "Deutsch"
    weight = 20
    [languages.de.params.jsonResume]
      present = "heute"
